dist: trusty
sudo: false

before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
  - sudo apt-get update
  - sudo apt-get install -y llvm-5.0 llvm-5.0-dev
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup

script:
  - stack test --ghc-options=-Werror

cache:
  directories:
    - $HOME/.stack
